// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dnd/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollInitiativeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollInitiativeRequest) Reset() {
	*x = RollInitiativeRequest{}
	mi := &file_dnd_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollInitiativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollInitiativeRequest) ProtoMessage() {}

func (x *RollInitiativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dnd_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollInitiativeRequest.ProtoReflect.Descriptor instead.
func (*RollInitiativeRequest) Descriptor() ([]byte, []int) {
	return file_dnd_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RollInitiativeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RollInitiativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollInitiativeResponse) Reset() {
	*x = RollInitiativeResponse{}
	mi := &file_dnd_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollInitiativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollInitiativeResponse) ProtoMessage() {}

func (x *RollInitiativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dnd_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollInitiativeResponse.ProtoReflect.Descriptor instead.
func (*RollInitiativeResponse) Descriptor() ([]byte, []int) {
	return file_dnd_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RollInitiativeResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_dnd_v1_service_proto protoreflect.FileDescriptor

const file_dnd_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14dnd/v1/service.proto\x12\x06dnd.v1\"'\n" +
	"\x15RollInitiativeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x16RollInitiativeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2Z\n" +
	"\aService\x12O\n" +
	"\x0eRollInitiative\x12\x1d.dnd.v1.RollInitiativeRequest\x1a\x1e.dnd.v1.RollInitiativeResponseB\x81\x01\n" +
	"\n" +
	"com.dnd.v1B\fServiceProtoP\x01Z,github.com/AranGarcia/droop/protoapis/dnd/v1\xa2\x02\x03DXX\xaa\x02\x06Dnd.V1\xca\x02\x06Dnd\\V1\xe2\x02\x12Dnd\\V1\\GPBMetadata\xea\x02\aDnd::V1b\x06proto3"

var (
	file_dnd_v1_service_proto_rawDescOnce sync.Once
	file_dnd_v1_service_proto_rawDescData []byte
)

func file_dnd_v1_service_proto_rawDescGZIP() []byte {
	file_dnd_v1_service_proto_rawDescOnce.Do(func() {
		file_dnd_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dnd_v1_service_proto_rawDesc), len(file_dnd_v1_service_proto_rawDesc)))
	})
	return file_dnd_v1_service_proto_rawDescData
}

var file_dnd_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dnd_v1_service_proto_goTypes = []any{
	(*RollInitiativeRequest)(nil),  // 0: dnd.v1.RollInitiativeRequest
	(*RollInitiativeResponse)(nil), // 1: dnd.v1.RollInitiativeResponse
}
var file_dnd_v1_service_proto_depIdxs = []int32{
	0, // 0: dnd.v1.Service.RollInitiative:input_type -> dnd.v1.RollInitiativeRequest
	1, // 1: dnd.v1.Service.RollInitiative:output_type -> dnd.v1.RollInitiativeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dnd_v1_service_proto_init() }
func file_dnd_v1_service_proto_init() {
	if File_dnd_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dnd_v1_service_proto_rawDesc), len(file_dnd_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dnd_v1_service_proto_goTypes,
		DependencyIndexes: file_dnd_v1_service_proto_depIdxs,
		MessageInfos:      file_dnd_v1_service_proto_msgTypes,
	}.Build()
	File_dnd_v1_service_proto = out.File
	file_dnd_v1_service_proto_goTypes = nil
	file_dnd_v1_service_proto_depIdxs = nil
}
