services:
  mongodb:
    image: 'mongo:8.0-rc-jammy'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: droop
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
    volumes:
      - type: bind
        source: docker/mongo
        target: /docker-entrypoint-initdb.d

  characters:
    depends_on:
      mongodb:
        restart: true
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/characters/Dockerfile
    ports:
      - 8090:8090
    environment:
      - MONGO_HOST=mongodb
    volumes:
      - ./proto/:/proto/
      - ./shared/:/shared/

  dnd:
    depends_on:
      - characters
    build:
      context: .
      dockerfile: docker/dnd/Dockerfile
    ports:
      - 8010:8010
    environment:
      - CHARACTERS_SERVICE_ADDR=characters
    volumes:
      - ./proto/:/proto/