services:
  mongodb:
    image: 'mongo:8.0-rc-jammy'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: droop
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
    volumes:
      - type: bind
        source: docker/mongo
        target: /docker-entrypoint-initdb.d

  redis:
    image: 'redis/redis-stack:6.2.6-v17'
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: '--requirepass password'

  kafka:
    image: "apache/kafka:3.9.0"
    ports:
      - 9092:9092
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
      interval: 15s
      timeout: 10s
      retries: 3

  characters:
    depends_on:
      mongodb:
        restart: true
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/characters/Dockerfile
    ports:
      - 8090:8090
    environment:
      - MONGO_HOST=mongodb
    volumes:
      - ./proto/:/proto/
      - ./shared/:/shared/

  dnd:
    depends_on:
      - characters
    build:
      context: .
      dockerfile: docker/dnd/Dockerfile
    ports:
      - 8010:8010
    environment:
      - CHARACTERS_SERVICE_ADDR=characters
    volumes:
      - ./proto/:/proto/