services:
  mongodb:
    image: 'mongo:8.0-rc-jammy'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: droop
    volumes:
      - type: bind
        source: docker/mongo
        target: /docker-entrypoint-initdb.d
