services:
  mongodb:
    image: mongo:8.0-rc-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: droop
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    #   interval: 5s
    volumes:
      - type: bind
        source: docker/mongo
        target: /docker-entrypoint-initdb.d

  redis:
    image: redis/redis-stack:6.2.6-v17
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: "--requirepass password"

  kafka:
    image: apache/kafka:3.9.0
    ports:
      - 9092:9092
    expose:
      - 9092
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  characters:
    # depends_on:
    #   mongodb:
    #     condition: service_healthy
    build:
      context: .
      dockerfile: docker/characters/Dockerfile
    ports:
      - 8090:8090
    environment:
      - MONGO_HOST=mongodb
    volumes:
      - ./proto/:/proto/
      - ./shared/:/shared/

  dnd:
    depends_on:
      - characters
    build:
      context: .
      dockerfile: docker/dnd/Dockerfile
    ports:
      - 8010:8010
    environment:
      - CHARACTERS_SERVICE_ADDR=characters
    volumes:
      - ./proto/:/proto/
