// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: initiatives/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterName string                 `protobuf:"bytes,3,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Result        int32                  `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTurnRequest) Reset() {
	*x = RegisterTurnRequest{}
	mi := &file_initiatives_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTurnRequest) ProtoMessage() {}

func (x *RegisterTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTurnRequest.ProtoReflect.Descriptor instead.
func (*RegisterTurnRequest) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTurnRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *RegisterTurnRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *RegisterTurnRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *RegisterTurnRequest) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type RegisterTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTurnResponse) Reset() {
	*x = RegisterTurnResponse{}
	mi := &file_initiatives_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTurnResponse) ProtoMessage() {}

func (x *RegisterTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTurnResponse.ProtoReflect.Descriptor instead.
func (*RegisterTurnResponse) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{1}
}

type ListTurnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsRequest) Reset() {
	*x = ListTurnsRequest{}
	mi := &file_initiatives_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsRequest) ProtoMessage() {}

func (x *ListTurnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsRequest.ProtoReflect.Descriptor instead.
func (*ListTurnsRequest) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListTurnsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type ListTurnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*Turn                `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTurnsResponse) Reset() {
	*x = ListTurnsResponse{}
	mi := &file_initiatives_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTurnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTurnsResponse) ProtoMessage() {}

func (x *ListTurnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTurnsResponse.ProtoReflect.Descriptor instead.
func (*ListTurnsResponse) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListTurnsResponse) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type ClearAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAllRequest) Reset() {
	*x = ClearAllRequest{}
	mi := &file_initiatives_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllRequest) ProtoMessage() {}

func (x *ClearAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllRequest.ProtoReflect.Descriptor instead.
func (*ClearAllRequest) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ClearAllRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type ClearAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAllResponse) Reset() {
	*x = ClearAllResponse{}
	mi := &file_initiatives_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAllResponse) ProtoMessage() {}

func (x *ClearAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAllResponse.ProtoReflect.Descriptor instead.
func (*ClearAllResponse) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{5}
}

type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_initiatives_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_initiatives_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_initiatives_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *Turn) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Turn) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *Turn) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_initiatives_v1_service_proto protoreflect.FileDescriptor

const file_initiatives_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1cinitiatives/v1/service.proto\x12\x0einitiatives.v1\"\x98\x01\n" +
	"\x13RegisterTurnRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12%\n" +
	"\x0echaracter_name\x18\x03 \x01(\tR\rcharacterName\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x05R\x06result\"\x16\n" +
	"\x14RegisterTurnResponse\"3\n" +
	"\x10ListTurnsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"?\n" +
	"\x11ListTurnsResponse\x12*\n" +
	"\x05turns\x18\x01 \x03(\v2\x14.initiatives.v1.TurnR\x05turns\"2\n" +
	"\x0fClearAllRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"\x12\n" +
	"\x10ClearAllResponse\"h\n" +
	"\x04Turn\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result2\x85\x02\n" +
	"\aService\x12Y\n" +
	"\fRegisterTurn\x12#.initiatives.v1.RegisterTurnRequest\x1a$.initiatives.v1.RegisterTurnResponse\x12P\n" +
	"\tListTurns\x12 .initiatives.v1.ListTurnsRequest\x1a!.initiatives.v1.ListTurnsResponse\x12M\n" +
	"\bClearAll\x12\x1f.initiatives.v1.ClearAllRequest\x1a .initiatives.v1.ClearAllResponseB\xb1\x01\n" +
	"\x12com.initiatives.v1B\fServiceProtoP\x01Z4github.com/AranGarcia/droop/protoapis/initiatives/v1\xa2\x02\x03IXX\xaa\x02\x0eInitiatives.V1\xca\x02\x0eInitiatives\\V1\xe2\x02\x1aInitiatives\\V1\\GPBMetadata\xea\x02\x0fInitiatives::V1b\x06proto3"

var (
	file_initiatives_v1_service_proto_rawDescOnce sync.Once
	file_initiatives_v1_service_proto_rawDescData []byte
)

func file_initiatives_v1_service_proto_rawDescGZIP() []byte {
	file_initiatives_v1_service_proto_rawDescOnce.Do(func() {
		file_initiatives_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_initiatives_v1_service_proto_rawDesc), len(file_initiatives_v1_service_proto_rawDesc)))
	})
	return file_initiatives_v1_service_proto_rawDescData
}

var file_initiatives_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_initiatives_v1_service_proto_goTypes = []any{
	(*RegisterTurnRequest)(nil),  // 0: initiatives.v1.RegisterTurnRequest
	(*RegisterTurnResponse)(nil), // 1: initiatives.v1.RegisterTurnResponse
	(*ListTurnsRequest)(nil),     // 2: initiatives.v1.ListTurnsRequest
	(*ListTurnsResponse)(nil),    // 3: initiatives.v1.ListTurnsResponse
	(*ClearAllRequest)(nil),      // 4: initiatives.v1.ClearAllRequest
	(*ClearAllResponse)(nil),     // 5: initiatives.v1.ClearAllResponse
	(*Turn)(nil),                 // 6: initiatives.v1.Turn
}
var file_initiatives_v1_service_proto_depIdxs = []int32{
	6, // 0: initiatives.v1.ListTurnsResponse.turns:type_name -> initiatives.v1.Turn
	0, // 1: initiatives.v1.Service.RegisterTurn:input_type -> initiatives.v1.RegisterTurnRequest
	2, // 2: initiatives.v1.Service.ListTurns:input_type -> initiatives.v1.ListTurnsRequest
	4, // 3: initiatives.v1.Service.ClearAll:input_type -> initiatives.v1.ClearAllRequest
	1, // 4: initiatives.v1.Service.RegisterTurn:output_type -> initiatives.v1.RegisterTurnResponse
	3, // 5: initiatives.v1.Service.ListTurns:output_type -> initiatives.v1.ListTurnsResponse
	5, // 6: initiatives.v1.Service.ClearAll:output_type -> initiatives.v1.ClearAllResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_initiatives_v1_service_proto_init() }
func file_initiatives_v1_service_proto_init() {
	if File_initiatives_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_initiatives_v1_service_proto_rawDesc), len(file_initiatives_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_initiatives_v1_service_proto_goTypes,
		DependencyIndexes: file_initiatives_v1_service_proto_depIdxs,
		MessageInfos:      file_initiatives_v1_service_proto_msgTypes,
	}.Build()
	File_initiatives_v1_service_proto = out.File
	file_initiatives_v1_service_proto_goTypes = nil
	file_initiatives_v1_service_proto_depIdxs = nil
}
