// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: characters/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,4,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	ArmorClass    int32                  `protobuf:"varint,5,opt,name=armor_class,json=armorClass,proto3" json:"armor_class,omitempty"`
	Strength      int32                  `protobuf:"varint,6,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,7,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Constitution  int32                  `protobuf:"varint,8,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Intelligence  int32                  `protobuf:"varint,9,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,10,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Charisma      int32                  `protobuf:"varint,11,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_characters_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CreateRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *CreateRequest) GetArmorClass() int32 {
	if x != nil {
		return x.ArmorClass
	}
	return 0
}

func (x *CreateRequest) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *CreateRequest) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *CreateRequest) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *CreateRequest) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *CreateRequest) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *CreateRequest) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_characters_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_characters_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_characters_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *string                `protobuf:"bytes,1,opt,name=class,proto3,oneof" json:"class,omitempty"`
	Level         *int32                 `protobuf:"varint,2,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	HealthPoints  *int32                 `protobuf:"varint,4,opt,name=health_points,json=healthPoints,proto3,oneof" json:"health_points,omitempty"`
	ArmorClass    *int32                 `protobuf:"varint,5,opt,name=armor_class,json=armorClass,proto3,oneof" json:"armor_class,omitempty"`
	Strength      *int32                 `protobuf:"varint,6,opt,name=strength,proto3,oneof" json:"strength,omitempty"`
	Dexterity     *int32                 `protobuf:"varint,7,opt,name=dexterity,proto3,oneof" json:"dexterity,omitempty"`
	Constitution  *int32                 `protobuf:"varint,8,opt,name=constitution,proto3,oneof" json:"constitution,omitempty"`
	Intelligence  *int32                 `protobuf:"varint,9,opt,name=intelligence,proto3,oneof" json:"intelligence,omitempty"`
	Wisdom        *int32                 `protobuf:"varint,10,opt,name=wisdom,proto3,oneof" json:"wisdom,omitempty"`
	Charisma      *int32                 `protobuf:"varint,11,opt,name=charisma,proto3,oneof" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_characters_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequest) GetClass() string {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return ""
}

func (x *UpdateRequest) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetHealthPoints() int32 {
	if x != nil && x.HealthPoints != nil {
		return *x.HealthPoints
	}
	return 0
}

func (x *UpdateRequest) GetArmorClass() int32 {
	if x != nil && x.ArmorClass != nil {
		return *x.ArmorClass
	}
	return 0
}

func (x *UpdateRequest) GetStrength() int32 {
	if x != nil && x.Strength != nil {
		return *x.Strength
	}
	return 0
}

func (x *UpdateRequest) GetDexterity() int32 {
	if x != nil && x.Dexterity != nil {
		return *x.Dexterity
	}
	return 0
}

func (x *UpdateRequest) GetConstitution() int32 {
	if x != nil && x.Constitution != nil {
		return *x.Constitution
	}
	return 0
}

func (x *UpdateRequest) GetIntelligence() int32 {
	if x != nil && x.Intelligence != nil {
		return *x.Intelligence
	}
	return 0
}

func (x *UpdateRequest) GetWisdom() int32 {
	if x != nil && x.Wisdom != nil {
		return *x.Wisdom
	}
	return 0
}

func (x *UpdateRequest) GetCharisma() int32 {
	if x != nil && x.Charisma != nil {
		return *x.Charisma
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_characters_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_characters_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_characters_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{7}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_characters_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{8}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_characters_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Class         string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,5,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	ArmorClass    int32                  `protobuf:"varint,6,opt,name=armor_class,json=armorClass,proto3" json:"armor_class,omitempty"`
	Strength      int32                  `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,8,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Constitution  int32                  `protobuf:"varint,9,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Intelligence  int32                  `protobuf:"varint,10,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,11,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Charisma      int32                  `protobuf:"varint,12,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_characters_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_characters_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_characters_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Character) GetArmorClass() int32 {
	if x != nil {
		return x.ArmorClass
	}
	return 0
}

func (x *Character) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Character) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *Character) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *Character) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Character) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *Character) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

var File_characters_v1_service_proto protoreflect.FileDescriptor

const file_characters_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bcharacters/v1/service.proto\x12\rcharacters.v1\"\xc5\x02\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"max_health\x18\x04 \x01(\x05R\tmaxHealth\x12\x1f\n" +
	"\varmor_class\x18\x05 \x01(\x05R\n" +
	"armorClass\x12\x1a\n" +
	"\bstrength\x18\x06 \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\a \x01(\x05R\tdexterity\x12\"\n" +
	"\fconstitution\x18\b \x01(\x05R\fconstitution\x12\"\n" +
	"\fintelligence\x18\t \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\n" +
	" \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bcharisma\x18\v \x01(\x05R\bcharisma\"H\n" +
	"\x0eCreateResponse\x126\n" +
	"\tcharacter\x18\x01 \x01(\v2\x18.characters.v1.CharacterR\tcharacter\"!\n" +
	"\x0fRetrieveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x10RetrieveResponse\x126\n" +
	"\tcharacter\x18\x01 \x01(\v2\x18.characters.v1.CharacterR\tcharacter\"\x96\x04\n" +
	"\rUpdateRequest\x12\x19\n" +
	"\x05class\x18\x01 \x01(\tH\x00R\x05class\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x02 \x01(\x05H\x01R\x05level\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12(\n" +
	"\rhealth_points\x18\x04 \x01(\x05H\x03R\fhealthPoints\x88\x01\x01\x12$\n" +
	"\varmor_class\x18\x05 \x01(\x05H\x04R\n" +
	"armorClass\x88\x01\x01\x12\x1f\n" +
	"\bstrength\x18\x06 \x01(\x05H\x05R\bstrength\x88\x01\x01\x12!\n" +
	"\tdexterity\x18\a \x01(\x05H\x06R\tdexterity\x88\x01\x01\x12'\n" +
	"\fconstitution\x18\b \x01(\x05H\aR\fconstitution\x88\x01\x01\x12'\n" +
	"\fintelligence\x18\t \x01(\x05H\bR\fintelligence\x88\x01\x01\x12\x1b\n" +
	"\x06wisdom\x18\n" +
	" \x01(\x05H\tR\x06wisdom\x88\x01\x01\x12\x1f\n" +
	"\bcharisma\x18\v \x01(\x05H\n" +
	"R\bcharisma\x88\x01\x01B\b\n" +
	"\x06_classB\b\n" +
	"\x06_levelB\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_health_pointsB\x0e\n" +
	"\f_armor_classB\v\n" +
	"\t_strengthB\f\n" +
	"\n" +
	"_dexterityB\x0f\n" +
	"\r_constitutionB\x0f\n" +
	"\r_intelligenceB\t\n" +
	"\a_wisdomB\v\n" +
	"\t_charisma\"H\n" +
	"\x0eUpdateResponse\x126\n" +
	"\tcharacter\x18\x01 \x01(\v2\x18.characters.v1.CharacterR\tcharacter\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vListRequest\"H\n" +
	"\fListResponse\x128\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x18.characters.v1.CharacterR\n" +
	"characters\"\xd1\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"max_health\x18\x05 \x01(\x05R\tmaxHealth\x12\x1f\n" +
	"\varmor_class\x18\x06 \x01(\x05R\n" +
	"armorClass\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\b \x01(\x05R\tdexterity\x12\"\n" +
	"\fconstitution\x18\t \x01(\x05R\fconstitution\x12\"\n" +
	"\fintelligence\x18\n" +
	" \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\v \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bcharisma\x18\f \x01(\x05R\bcharisma2\xec\x02\n" +
	"\aService\x12E\n" +
	"\x06Create\x12\x1c.characters.v1.CreateRequest\x1a\x1d.characters.v1.CreateResponse\x12K\n" +
	"\bRetrieve\x12\x1e.characters.v1.RetrieveRequest\x1a\x1f.characters.v1.RetrieveResponse\x12E\n" +
	"\x06Update\x12\x1c.characters.v1.UpdateRequest\x1a\x1d.characters.v1.UpdateResponse\x12E\n" +
	"\x06Delete\x12\x1c.characters.v1.DeleteRequest\x1a\x1d.characters.v1.DeleteResponse\x12?\n" +
	"\x04List\x12\x1a.characters.v1.ListRequest\x1a\x1b.characters.v1.ListResponseB\xab\x01\n" +
	"\x11com.characters.v1B\fServiceProtoP\x01Z3github.com/AranGarcia/droop/protoapis/characters/v1\xa2\x02\x03CXX\xaa\x02\rCharacters.V1\xca\x02\rCharacters\\V1\xe2\x02\x19Characters\\V1\\GPBMetadata\xea\x02\x0eCharacters::V1b\x06proto3"

var (
	file_characters_v1_service_proto_rawDescOnce sync.Once
	file_characters_v1_service_proto_rawDescData []byte
)

func file_characters_v1_service_proto_rawDescGZIP() []byte {
	file_characters_v1_service_proto_rawDescOnce.Do(func() {
		file_characters_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_characters_v1_service_proto_rawDesc), len(file_characters_v1_service_proto_rawDesc)))
	})
	return file_characters_v1_service_proto_rawDescData
}

var file_characters_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_characters_v1_service_proto_goTypes = []any{
	(*CreateRequest)(nil),    // 0: characters.v1.CreateRequest
	(*CreateResponse)(nil),   // 1: characters.v1.CreateResponse
	(*RetrieveRequest)(nil),  // 2: characters.v1.RetrieveRequest
	(*RetrieveResponse)(nil), // 3: characters.v1.RetrieveResponse
	(*UpdateRequest)(nil),    // 4: characters.v1.UpdateRequest
	(*UpdateResponse)(nil),   // 5: characters.v1.UpdateResponse
	(*DeleteRequest)(nil),    // 6: characters.v1.DeleteRequest
	(*DeleteResponse)(nil),   // 7: characters.v1.DeleteResponse
	(*ListRequest)(nil),      // 8: characters.v1.ListRequest
	(*ListResponse)(nil),     // 9: characters.v1.ListResponse
	(*Character)(nil),        // 10: characters.v1.Character
}
var file_characters_v1_service_proto_depIdxs = []int32{
	10, // 0: characters.v1.CreateResponse.character:type_name -> characters.v1.Character
	10, // 1: characters.v1.RetrieveResponse.character:type_name -> characters.v1.Character
	10, // 2: characters.v1.UpdateResponse.character:type_name -> characters.v1.Character
	10, // 3: characters.v1.ListResponse.characters:type_name -> characters.v1.Character
	0,  // 4: characters.v1.Service.Create:input_type -> characters.v1.CreateRequest
	2,  // 5: characters.v1.Service.Retrieve:input_type -> characters.v1.RetrieveRequest
	4,  // 6: characters.v1.Service.Update:input_type -> characters.v1.UpdateRequest
	6,  // 7: characters.v1.Service.Delete:input_type -> characters.v1.DeleteRequest
	8,  // 8: characters.v1.Service.List:input_type -> characters.v1.ListRequest
	1,  // 9: characters.v1.Service.Create:output_type -> characters.v1.CreateResponse
	3,  // 10: characters.v1.Service.Retrieve:output_type -> characters.v1.RetrieveResponse
	5,  // 11: characters.v1.Service.Update:output_type -> characters.v1.UpdateResponse
	7,  // 12: characters.v1.Service.Delete:output_type -> characters.v1.DeleteResponse
	9,  // 13: characters.v1.Service.List:output_type -> characters.v1.ListResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_characters_v1_service_proto_init() }
func file_characters_v1_service_proto_init() {
	if File_characters_v1_service_proto != nil {
		return
	}
	file_characters_v1_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_characters_v1_service_proto_rawDesc), len(file_characters_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_characters_v1_service_proto_goTypes,
		DependencyIndexes: file_characters_v1_service_proto_depIdxs,
		MessageInfos:      file_characters_v1_service_proto_msgTypes,
	}.Build()
	File_characters_v1_service_proto = out.File
	file_characters_v1_service_proto_goTypes = nil
	file_characters_v1_service_proto_depIdxs = nil
}
