# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Install buf
      uses: bufbuild/buf-action@v1

    - name: Compile protocol buffers
      run: make proto

    - name: Build services
      run: |
        go build -v ./services/characters/...
        go build -v ./services/dnd/...
        go build -v ./services/initiatives/...

    - name: Test services
      run: |
        go test -v ./services/characters/...
        go test -v ./services/dnd/...
        go test -v ./services/initiatives/...